@startuml
actor Bob #red
participant Alice
participant "у меня очень\n длинное имя" asL #99FF99
Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->L: Log transaction
@enduml