@startuml
skinparam class {
BackgroundColor LightGreen

ArrowColor Blue
BorderColor Red
BackgroundColor<<Foo>> Green
Border Color<<Foo>> Orange
}
skinparam stereotypeCBackgroundColor Magenta
skinparam stereotypeCBackgroundColor<< Foo >> Gray
Class01 <<<<Foo>> 
Class03 <<Foo>>
Class01 "к одному" *- "от многих" Class02 : композиция
Class03 0-- Class04 : агрегация
@enduml